server:
  port: 8065
  servlet:
    context-path: /api/1.0
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: development
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: root
    password: # no password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

security:
  jwt:
    token:
      secret: secret
      expire: 300000 # 1 hour
